[package]
name = "ataraxia"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcstr = "1.1.5"
eyre = "0.6.11"
imbl = "2.0.3"
once_cell = "1.19.0"
parking_lot = "0.12.1"
tinyvec = "1.6.0"
